<?php

use Drupal\node\Entity\Node;


function basic_page2_entity_insert(Drupal\Core\Entity\EntityInterface $entity)
{
    $user = \Drupal::currentUser();

    if ($entity->getEntityType()->id() == 'node' && $entity->bundle() == 'sample_content') {
        $node = Node::create(array(
            'type' => 'task',
            'title' => 'New task created for you',
            'langcode' => 'en',
            'uid' => $user->id(),
            'status' => 1,
            'field_reference' => array(
                'task_reference' => 'this is sample task reference'
            ),
        ));
        $node->save();
    }
}

function basic_page2_views_query_alter(Drupal\views\ViewExecutable $view,  Drupal\views\Plugin\views\query\Sql $query)
{
    if ($view->id() == 'news') {

        $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
        $fields  = $account->get('field_assign_s')->getValue();

        $state_ids = array_column($fields, 'target_id');
        // echo "<pre>";
        // print_r($state_ids);    
        // die();
        if (!empty($state_ids)) {
            foreach ($query->where as &$condition_group) {
                foreach ($condition_group['conditions'] as &$condition) {
                    if ($condition['field'] == 'node__field_states.field_states_target_id = :node__field_states_field_states_target_id') {
                        $condition = [
                            'field' => 'node__field_states.field_states_target_id',
                            'value' => $state_ids,
                            'operator' => 'IN',
                        ];
                    }
                }
            }
        }
    }
}
